{
  "name": "nas-garden",
  "services": {
    "api": {
      "image": "sha256:1102bfe49106d3c6c50eb45bced10b45d84e86b6fa12de8a8801e0f6a98ebfd6",
      "pull_policy": "never",
      "container_name": "garden-api",
      "restart": "unless-stopped",
      "env_file": [
        {
          "path": "./garden-api.env",
          "format": "raw"
        }
      ],
      "networks": [
        "garden"
      ],
      "volumes": [
        "./backend:/app/server:ro",
        "./data:/data/garden"
      ],
      "command": [
        "node",
        "--no-warnings",
        "/app/server/index.mjs"
      ],
      "user": "1000:1001",
      "working_dir": "/"
    }
  },
  "networks": {
    "garden": {
      "external": true,
      "name": "garden-net"
    }
  }
}
